[pytest]
addopts =
    --cov=custom_components.anker_solix_official
    --cov-report=xml:reports/coverage.xml
    --cov-report=term-missing
    --junit-xml=junit.xml
asyncio_mode = auto
testpaths = tests
